import { BasedbError } from '../errors/index.js'
import { formulaDialect } from '../formula/language.js'
import type { Pools } from '../runtime/pool.js'
import type { RequestContext } from '../tx/context.js'
import { DOCUMENT_MAX_BYTES, documentCache, etagFor } from './cache.js'
import { toDocumentation } from './documentation.js'
import { toBaseList, toMeta } from './meta.js'
import { toOpenApi } from './openapi.js'
import { ofEnvironment, project, referenceIn, snapshot } from './projection.js'

/**
 * Serving the catalog projections, with validator — chapter 08 §9.2.
 *
 * Produced on demand, in memory. NEVER stored in the database, never regenerated by a
 * background job: a stored specification is a specification that drifts, and the day a
 * migration forgets to refresh it, the API and its contract contradict each other.
 *
 * The composition lives here rather than in the HTTP adapter because the `304` has a
 * property worth protecting: it is served WITHOUT REBUILDING the document. An adapter
 * that built first and compared afterwards would answer the same bytes, and would have
 * paid the whole cost to do it.
 */

export type MetaKind = 'bases' | 'meta' | 'openapi' | 'doc'

export interface ServedMeta {
  readonly etag: string
  /** True when the caller's validator still holds: nothing was built. */
  readonly notModified: boolean
  /** Absent on a `304`. */
  readonly body?: unknown
  /** Serialized size, for the bound of §9.2. */
  readonly bytes: number
}

/**
 * `Cache-Control` of §9.2.
 *
 * NOT `no-store`: it would forbid the client from keeping the response, hence the
 * validator, hence from sending `If-None-Match` — and the announced `304` would never
 * happen. `private` because two readers get two different documents.
 */
export const CACHE_CONTROL = 'private, max-age=0, must-revalidate'
/** The documentation is written in the language of the screen that asks for it. */
export const VARY =
  'Authorization, Accept-Encoding, X-Basedb-Locale, Accept-Language, X-Basedb-Environment'

/**
 * Serves one of the four catalog documents.
 *
 * `reference` is the base, empty for the listing. `ifNoneMatch` is the caller's
 * validator, as their browser or their client sends it back. `language` is the reader's:
 * the documentation is written in it, and a base's description gives its formulas in
 * French or in English according to it (`formulaDialect`).
 */
export async function serveMeta(
  pools: Pools,
  ctx: RequestContext,
  kind: MetaKind,
  reference: string,
  ifNoneMatch?: string,
  language = 'fr',
): Promise<ServedMeta> {
  const { grants, raw, versions } = await snapshot(pools, ctx)
  const dialect = formulaDialect(language)

  // The validator is computed from the counters alone — never from the bytes. That is
  // what lets the next two lines end the request. Two languages are two documents, so
  // the documentation's validator — and its place in the cache — includes the language,
  // and a base's description's, the language of its formulas. An environment asked
  // names another base, or another listing: it is part of the key too.
  const where = ctx.environment === null ? reference : `${reference}@${ctx.environment}`
  const etag = etagFor(
    ctx,
    versions,
    grants,
    kind === 'bases' ? 'meta' : kind,
    kind === 'doc' ? `${where}|${language}` : kind === 'meta' ? `${where}|${dialect}` : where,
  )

  if (ifNoneMatch !== undefined && matches(ifNoneMatch, etag)) {
    return { etag, notModified: true, bytes: 0 }
  }

  const cached = documentCache.get(etag, versions, Date.now())
  if (cached !== undefined) {
    return { etag, notModified: false, body: JSON.parse(cached), bytes: cached.length }
  }

  // With an environment asked, the listing shows that environment of each base.
  const bases = ofEnvironment(ctx, raw.bases, project(ctx, grants, raw, dialect))

  let body: unknown
  if (kind === 'bases') {
    body = toBaseList(
      bases.map((b) => ({
        id: b.id,
        name: b.name,
        label: b.label,
        description: b.description,
        color: b.color,
        icon: b.icon,
        image: b.image,
        project: b.project,
        environment: b.environment,
        tableCount: b.tables.length,
      })),
    )
  } else {
    const ref = referenceIn(ctx, raw.bases, reference)
    const found = bases.find((b) => b.name === ref || b.id === ref)
    // A base with no readable table is absent from the projection, so it lands here —
    // the same refusal as a base that does not exist, which is the point.
    if (found === undefined) {
      throw new BasedbError('RESOURCE_NOT_FOUND', { details: { base: reference } })
    }
    body =
      kind === 'openapi'
        ? toOpenApi(found, ctx.tenantId)
        : kind === 'doc'
          ? toDocumentation(found, ctx.tenantId, language)
          : toMeta(found)
  }

  const serialized = JSON.stringify(body)

  // Beyond the bound, generation is REFUSED rather than truncated: a 500-table base
  // serializes to some 6 MiB, and a client that receives half a contract is worse off
  // than one that receives none.
  if (serialized.length > DOCUMENT_MAX_BYTES) {
    throw new BasedbError('REQUEST_INVALID', {
      details: {
        parameter: 'tables',
        hint: 'Base trop volumineuse pour être décrite en une fois : précisez ?tables=<liste>.',
        maximum_bytes: DOCUMENT_MAX_BYTES,
      },
    })
  }

  documentCache.set(etag, versions, Date.now(), serialized)
  return { etag, notModified: false, body, bytes: serialized.length }
}

/**
 * Compares a validator with the one we hold.
 *
 * `If-None-Match` may carry a list, and a proxy may weaken an entry with `W/`. Both are
 * accepted: a weak comparison is the right one for a cache validation.
 */
function matches(ifNoneMatch: string, etag: string): boolean {
  if (ifNoneMatch.trim() === '*') return true
  return ifNoneMatch
    .split(',')
    .map((candidate) => candidate.trim().replace(/^W\//, ''))
    .includes(etag)
}
