/**
 * `@basedb/contracts` — the only vocabulary shared between the server, the front end
 * and the SDK: types, public payload shapes and the error code registry.
 *
 * The registry is GENERATED from the annex of chapter 00 (A23), which remains the
 * source of truth: `node scripts/generate-error-codes.mjs`.
 */

export {
  ALL_ERROR_CODES,
  ERROR_CODES,
  httpStatusFor,
  isErrorCode,
  type ErrorCode,
  type ErrorCodeEntry,
  type ErrorDomain,
} from './error-codes.js'

export {
  AGGREGATION_FNS,
  CARD_KINDS,
  COLUMNLESS_FNS,
  DASHBOARD_COLUMNS,
  DASHBOARD_LIMITS,
  DASHBOARD_ROW_HEIGHT,
  FILTER_OPS,
  JOIN_KINDS,
  MAP_REGIONS,
  NUMBER_OPERATORS,
  PARAMETER_TYPES,
  QUERY_LIMITS,
  SQL_FILTER_KINDS,
  SQL_VARIABLE_TYPES,
  TEMPORAL_EXTRACTIONS,
  TEMPORAL_UNITS,
  VISUALIZATIONS,
  addDays,
  cardConstraints,
  cardSize,
  cardsFromBlocks,
  citedNames,
  columnName,
  finerUnit,
  flowLayout,
  isTemporalUnit,
  parameterFits,
  parameterFitsVariable,
  parameterHasValue,
  periodExpression,
  placedAfter,
  questionCards,
  resolveDateExpression,
  resultNames,
  ruleColor,
  ruleHolds,
  sameColumnRef,
  sortTerms,
  sqlVariableNames,
  startOfPeriod,
  tiesItself,
  variableCard,
  withoutVariables,
  type Aggregation,
  type AggregationFn,
  type Breakout,
  type BuilderQuery,
  type CardKind,
  type CardMapping,
  type ColorRule,
  type ColumnRef,
  type Constraint,
  type DashboardCard,
  type DashboardParameter,
  type DashboardTab,
  type DaySpan,
  type Filter,
  type FilterOp,
  type FilterValue,
  type Join,
  type JoinKind,
  type LegacyBlock,
  type MapRegion,
  type NumberOperator,
  type OrderBy,
  type ParameterTarget,
  type ParameterType,
  type ParameterValue,
  type QueryResult,
  type QuestionQuery,
  type ResultColumn,
  type SeriesSettings,
  type SortTarget,
  type SqlFilterKind,
  type SqlQuery,
  type SqlVariable,
  type SqlVariableType,
  type TemporalExtraction,
  type TemporalTruncation,
  type TemporalUnit,
  type TextVariable,
  type TiedVariable,
  type Visualization,
  type VisualizationSettings,
  type VisualizationType,
} from './analytics.js'

export type {
  DashboardChange,
  DashboardCopilotAction,
  DashboardCopilotAnswer,
  DashboardCopilotRead,
  DashboardContent,
} from './dashboard-copilot.js'

export {
  TEMPLATE_AI_KINDS,
  TEMPLATE_COMPUTED_KINDS,
  TEMPLATE_DISPLAY_KINDS,
  TEMPLATE_FIELD_KINDS,
  TEMPLATE_FORM_KINDS,
  TEMPLATE_FORMAT,
  TEMPLATE_LIMITS,
  TEMPLATE_VIEW_KINDS,
  VIEW_FIELD_KEYS,
  checkTemplate,
  citedInText,
  citedLabels,
  labelKey,
  optionValue,
  resolveTemplateDate,
  summarizeTemplate,
  translateFilter,
  type ResolvedField,
  type Template,
  type TemplateAction,
  type TemplateAutomation,
  type TemplateBlock,
  type TemplateCheck,
  type TemplateDashboard,
  type TemplateField,
  type TemplateFieldKind,
  type TemplateFormat,
  type TemplateIssue,
  type TemplateLink,
  type TemplateOption,
  type TemplateRow,
  type TemplateSummary,
  type TemplateTable,
  type TemplateValue,
  type TemplateView,
  type TemplateViewKind,
} from './templates.js'

export {
  localizeTemplate,
  templateTexts,
  type TemplateDictionary,
  type TemplateText,
  type TemplateTextKind,
} from './template-i18n.js'

export {
  FORMULA_ENGLISH,
  formulaDialect,
  formulaInEnglish,
  type FormulaDialect,
} from './formula-words.js'

export {
  FALLBACK_LOCALE,
  LOCALES,
  LOCALE_NAMES,
  SOURCE_LOCALE,
  acceptedLanguages,
  isLocale,
  localeOfTag,
  matchLocale,
  type Locale,
} from './locales.js'

export {
  FORM_ALIGNS,
  FORM_CONDITION_OPS,
  FORM_FONTS,
  FORM_PREFILLS,
  FORM_PREFILL_KINDS,
  FORM_THEMES,
  conditionHolds,
  conditionNeedsValue,
  isEmptyAnswer,
  visibleQuestions,
  type FormAlign,
  type FormCondition,
  type FormConditionOp,
  type FormFont,
  type FormPrefill,
  type FormTheme,
} from './forms.js'

export {
  QUIZ_KINDS,
  QUIZ_MAX_ACCEPTED,
  QUIZ_MAX_POINTS,
  QUIZ_REVEALS,
  QUIZ_TEXT_KINDS,
  isRightAnswer,
  looseText,
  quizAnswerFits,
  quizPassed,
  quizPercent,
  scoreQuiz,
  type QuizAnswer,
  type QuizMark,
  type QuizQuestion,
  type QuizReveal,
  type QuizScore,
} from './quiz.js'
