// List of PostgreSQL reserved keywords, extracted from `pg_get_keywords()`.
//
// Source: PostgreSQL 16.15 (A1 — PostgreSQL 16 minimum).
// Filter: `catcode IN ('R', 'T', 'C')`, per chapter 01 §4.
//
// The original `catcode` is kept so the extraction can be replayed across a major
// version change:
//   R — reserved            : can never be a name without quoting
//   T — type_func_name      : reserved in type and function names
//   C — col_name            : accepted as a column name, but `SELECT timestamp FROM t`
//                             is confusing at best, a syntax error at worst
//
// This list only filters the assignment of NEW names (chapter 01 §4): a word that
// becomes reserved later breaks no existing name, since basedb always quotes.
//
// Regenerate with:
//   psql -t -A -F',' -c "SELECT word, catcode FROM pg_get_keywords()
//                        WHERE catcode IN ('R','T','C') ORDER BY word;"

export type Catcode = 'R' | 'T' | 'C'

export const RESERVED_WORDS: ReadonlyMap<string, Catcode> = new Map([
  ['all', 'R'],
  ['analyse', 'R'],
  ['analyze', 'R'],
  ['and', 'R'],
  ['any', 'R'],
  ['array', 'R'],
  ['as', 'R'],
  ['asc', 'R'],
  ['asymmetric', 'R'],
  ['authorization', 'T'],
  ['between', 'C'],
  ['bigint', 'C'],
  ['binary', 'T'],
  ['bit', 'C'],
  ['boolean', 'C'],
  ['both', 'R'],
  ['case', 'R'],
  ['cast', 'R'],
  ['char', 'C'],
  ['character', 'C'],
  ['check', 'R'],
  ['coalesce', 'C'],
  ['collate', 'R'],
  ['collation', 'T'],
  ['column', 'R'],
  ['concurrently', 'T'],
  ['constraint', 'R'],
  ['create', 'R'],
  ['cross', 'T'],
  ['current_catalog', 'R'],
  ['current_date', 'R'],
  ['current_role', 'R'],
  ['current_schema', 'T'],
  ['current_time', 'R'],
  ['current_timestamp', 'R'],
  ['current_user', 'R'],
  ['dec', 'C'],
  ['decimal', 'C'],
  ['default', 'R'],
  ['deferrable', 'R'],
  ['desc', 'R'],
  ['distinct', 'R'],
  ['do', 'R'],
  ['else', 'R'],
  ['end', 'R'],
  ['except', 'R'],
  ['exists', 'C'],
  ['extract', 'C'],
  ['false', 'R'],
  ['fetch', 'R'],
  ['float', 'C'],
  ['for', 'R'],
  ['foreign', 'R'],
  ['freeze', 'T'],
  ['from', 'R'],
  ['full', 'T'],
  ['grant', 'R'],
  ['greatest', 'C'],
  ['group', 'R'],
  ['grouping', 'C'],
  ['having', 'R'],
  ['ilike', 'T'],
  ['in', 'R'],
  ['initially', 'R'],
  ['inner', 'T'],
  ['inout', 'C'],
  ['int', 'C'],
  ['integer', 'C'],
  ['intersect', 'R'],
  ['interval', 'C'],
  ['into', 'R'],
  ['is', 'T'],
  ['isnull', 'T'],
  ['join', 'T'],
  ['json_array', 'C'],
  ['json_arrayagg', 'C'],
  ['json_object', 'C'],
  ['json_objectagg', 'C'],
  ['lateral', 'R'],
  ['leading', 'R'],
  ['least', 'C'],
  ['left', 'T'],
  ['like', 'T'],
  ['limit', 'R'],
  ['localtime', 'R'],
  ['localtimestamp', 'R'],
  ['national', 'C'],
  ['natural', 'T'],
  ['nchar', 'C'],
  ['none', 'C'],
  ['normalize', 'C'],
  ['not', 'R'],
  ['notnull', 'T'],
  ['null', 'R'],
  ['nullif', 'C'],
  ['numeric', 'C'],
  ['offset', 'R'],
  ['on', 'R'],
  ['only', 'R'],
  ['or', 'R'],
  ['order', 'R'],
  ['out', 'C'],
  ['outer', 'T'],
  ['overlaps', 'T'],
  ['overlay', 'C'],
  ['placing', 'R'],
  ['position', 'C'],
  ['precision', 'C'],
  ['primary', 'R'],
  ['real', 'C'],
  ['references', 'R'],
  ['returning', 'R'],
  ['right', 'T'],
  ['row', 'C'],
  ['select', 'R'],
  ['session_user', 'R'],
  ['setof', 'C'],
  ['similar', 'T'],
  ['smallint', 'C'],
  ['some', 'R'],
  ['substring', 'C'],
  ['symmetric', 'R'],
  ['system_user', 'R'],
  ['table', 'R'],
  ['tablesample', 'T'],
  ['then', 'R'],
  ['time', 'C'],
  ['timestamp', 'C'],
  ['to', 'R'],
  ['trailing', 'R'],
  ['treat', 'C'],
  ['trim', 'C'],
  ['true', 'R'],
  ['union', 'R'],
  ['unique', 'R'],
  ['user', 'R'],
  ['using', 'R'],
  ['values', 'C'],
  ['varchar', 'C'],
  ['variadic', 'R'],
  ['verbose', 'T'],
  ['when', 'R'],
  ['where', 'R'],
  ['window', 'R'],
  ['with', 'R'],
  ['xmlattributes', 'C'],
  ['xmlconcat', 'C'],
  ['xmlelement', 'C'],
  ['xmlexists', 'C'],
  ['xmlforest', 'C'],
  ['xmlnamespaces', 'C'],
  ['xmlparse', 'C'],
  ['xmlpi', 'C'],
  ['xmlroot', 'C'],
  ['xmlserialize', 'C'],
  ['xmltable', 'C'],
])

/** Vrai si le candidat est un mot-clé réservé au sens du chapitre 01 §4. */
export function isReservedWord(candidate: string): boolean {
  return RESERVED_WORDS.has(candidate)
}
